### PR TITLE
Add configuration option for filename used by buildTar goal of maven plugin (#1561)

### LINKED ISSUE #1561: Add configuration option for filename used by buildTar goal of maven plugin
The current (as of 1.0.2) maven plugin has the very useful goal of buildTar which creates a docker tar image named "jib-maven.tar".  It would be very convenient for their to be a configuration option to control the filename for situations when the version or other data needs to be placed into the filename.

Issue #1282 suggests using a separate plugin to accomplish this, but this is awkward at best.  So in this issue I'm requesting specifically that an option be added to allow setting the filename directly by the jib-maven-plugin.

### PR DESCRIPTION
**Pull request by hoppermann**
Hello,

in our projects, we also have the need to specify the file name of the tar file. For this we have created this pull request.

Fix #1561

### CODE REVIEW

**Comment by hoppermann** [comment]
@googlebot I signed it!

**Comment by hoppermann** [comment]
@googlebot I fixed it.

**Comment by hoppermann** [comment]
@googlebot I consent.

**Comment by chanseokoh** [comment]
Thank you @hoppermann. We really welcome external contributions. We will get back to you, though this may take some time, as we need to have an internal discussion.

Looks like Lukas Rohr authored the commit. I can't find their GitHub name. Can you tell Lukas Rohr to leave a comment `@googlebot I consent.`?

**Comment by kartoffelcake** [comment]
@googlebot I consent.

**Comment by chanseokoh** [comment]
@googlebot I fixed it.

**Comment by chanseokoh** [comment]
Hi @hoppermann,

Sorry for the delay. We decided to have three separate configuration parameters for each of the ID, digest, and tar files. Not only that, we want to allow specifying full path (absolute or relative to the build output directory). So, for Maven, the configuration would look like this:

```xml
<outputFiles>
    <!-- goes into target/digest.txt (default: jib-image.digest) -->
    <digest>digest.txt</digest>
    <!-- target/jib-output/helloworld.image.tar -->
    <tar>jib-output/helloworld-image.tar</tar>
    <id>/tmp/jib-build/jib-image.id</id>
</outputFiles>
```

Would you be willing to update the PR accordingly? If you don't have time or resources to follow up, that's fine. We can take over from where you left.

**Comment by hoppermann** [comment]
Hello @chanseokoh,

feel free to take over the pull request.
I think it is better if you make the changes to meet your requirements.

**Comment by codeseedr** [comment]
Hello @chanseokoh, I'm interested in this. Any plans on delivering it soon? If not, perhaps I could contribute?

**Comment by chanseokoh** [comment]
@codeseedr yeah, we haven't had a chance to work on this. You can certainly pick this up where @hoppermann left and modify to implement what we decided in https://github.com/GoogleContainerTools/jib/pull/1921#issuecomment-526338725. We welcome contributions.

**Comment by TadCordle** [comment]
Closing for now in favor of:
* #2024 - Formal design proposal based on @chanseokoh's earlier comment in this thread
* #2025 - Implementation of said proposal (subject to change if there are suggestions on the proposal)

Thanks everyone who offered to help!

**Pull request closed without merging**
