### PR TITLE
Ignore DirectoryNotEmptyException too since it is what is thrown on L…

### LINKED ISSUE #1273: [gradle] Concurrency issue with many simultaneous builds
**Description of the issue**: In a project that can run dozens of jib build tasks concurrently, an exception was thrown when working with the cache

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 133 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.FileSystemException: /root/.cache/google-cloud-tools-java/jib/tmp/10954747174794241924 -> /root/.cache/google-cloud-tools-java/jib/layers/096ebeedeeb6534eadf6d1ae8173145e8f43aedf29f5ae179f8b2e899f84f344: Directory not empty
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.moveIfDoesNotExist(DefaultCacheStorageWriter.java:75)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.write(DefaultCacheStorageWriter.java:154)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorage.write(DefaultCacheStorage.java:74)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Cache.writeCompressedLayer(Cache.java:68)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:81)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:36)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
Step #3 - "curio-generated-build-all": 
```

**Expected behavior**: The build succeeds

**Steps to reproduce**:  This only happens sometimes, and on a build with dozens of projects. I suspect it will be hard to reproduce with a small build.

**Environment**: Linux, Gradle 5.0-rc-4, Java 11, gradle-jib-plugin 0.10.0

**`jib-gradle-plugin` Configuration**: 

Standard configuration, just lots of subprojects

**Log output**:

```
Step #3 - "curio-generated-build-all": Caused by: com.google.cloud.tools.jib.plugins.common.BuildStepsExecutionException: Build image failed
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.plugins.common.BuildStepsRunner.build(BuildStepsRunner.java:269)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.gradle.BuildImageTask.buildImage(BuildImageTask.java:119)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Step #3 - "curio-generated-build-all": at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Step #3 - "curio-generated-build-all": at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
Step #3 - "curio-generated-build-all": ... 133 more
Step #3 - "curio-generated-build-all": Caused by: java.nio.file.FileSystemException: /root/.cache/google-cloud-tools-java/jib/tmp/10954747174794241924 -> /root/.cache/google-cloud-tools-java/jib/layers/096ebeedeeb6534eadf6d1ae8173145e8f43aedf29f5ae179f8b2e899f84f344: Directory not empty
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.moveIfDoesNotExist(DefaultCacheStorageWriter.java:75)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorageWriter.write(DefaultCacheStorageWriter.java:154)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.DefaultCacheStorage.write(DefaultCacheStorage.java:74)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.cache.Cache.writeCompressedLayer(Cache.java:68)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:81)
Step #3 - "curio-generated-build-all": at com.google.cloud.tools.jib.builder.steps.PullAndCacheBaseImageLayerStep.call(PullAndCacheBaseImageLayerStep.java:36)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:125)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:57)
Step #3 - "curio-generated-build-all": at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:78)
Step #3 - "curio-generated-build-all": 
```

**Additional Information**: 

The OS is Linux (more specifically Google's Cloud Build VM with a build image based on debian), so I think atomic moves should work and would not expect #1044 to be related.

### PR DESCRIPTION
**Pull request by anuraaga**
…inux when trying to atomically move a directory to an existing one.

Fixes #1273

### CODE REVIEW

**Comment by chanseokoh** [comment]
I think we should look into this more to verify if this is indeed the right fix. From my experience on my machine, `DirectoryNotEmptyException` was misleading in that it was not saying that the destination is not empty but rather was the case that the source directory could not be unlinked because the source was not empty, although the situation was that the atomic operation was not supported and the move degraded to copy-and-delete.

**Comment by anuraaga** [comment]
Yeah there are so many platform-specific issues here that I'm not confident in the fix either, welcome for any tips on how we can be more sure. Since this is for the atomic-move codepath, I believe it's ok on most Unix. But indeed, since Java explicitly says the semantics are platform-specific, maybe a total rethink with file locks would be more cross-platform.

**Comment by briandealwis** [comment]
From your stack trace in #1273, it seems that a `FileSystemException` is being thrown, not a `DirectoryNotEmptyException`.

From examining the code, `LinuxFileSystemProvider` inherits `UnixFileSystemProvider#move()` which delegates to `UnixCopyFile#move()`.  When `ATOMIC_MOVE` is set, then it calls out to native code in `UnixNativeDispatcher` that calls the `rename(2)` system call.  On an error, `UnixNativeDispatcher` throws a `UnixException`, and `UnixException#translateToIOExceptoin()` turns an `ENOTEMPTY` into a `FileSystemException`.

**Comment by anuraaga** [comment]
Ah thanks for digging and looking at the internal implementation! Closing this since it's not related

**Pull request closed without merging**
