### PR TITLE
Inherit USER from base image

### LINKED ISSUE #2421: USER not respected / java running as root user
**Environment**:

- jib-maven-plugin, 2.2.0
- maven
- windows

**Description of the issue**:
The java application is run as root user, the dockerfile initializes for a different user.
The application is failing due to the wrong user context, in this specific case the base image is selenium/node-firefox and user is seluser.

**Expected behavior**:
The java application is run as the user specified by the Dockerfile.

**Steps to reproduce**:

  1. use seluser as base image
  2. set the entrypoint to whoami

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #2421.

I think we never inherited USER.

### CODE REVIEW

**Comment by loosebazooka** [comment]
I wonder if some discussion led us to do this? Would this break existing builds that depend on ignoring user?

**Comment by chanseokoh** [comment]
Hmm... good point. I don't remember such a thing though. Let me search.

**Comment by chanseokoh** [comment]
In #595, we had been gradually expanding configurations to inherit. Inheriting `User` was also [considered](https://github.com/GoogleContainerTools/jib/issues/595#issuecomment-440399731), but no further action was taken.

I do think there will be users whose images we will break with this change. `User` has a more significant impact than other configurations. However, I think we should eventually fix this. `Dockerfile` inherits it too.

**Comment by loosebazooka** [comment]
Sure then this should be a 2.3.0?

**Comment by loosebazooka** [comment]
Just curious though, can a user override the inherited user?

**Comment by chanseokoh** [comment]
Yes, with `jib.container.user`. A test in this PR covers that.

**Pull request merged**
