### PR TITLE
Also looks for registry credential files in XDG folders

### PR DESCRIPTION
**Pull request by sv3ndk**
This PR is my proposition for addressing https://github.com/GoogleContainerTools/jib/issues/3524 . This is my first contribution to this project, don't hesitate to let me know if I failed to follow any convention.

This PR adds 2 locations, based on the XDG base directory specification, to the list of places where Jib looks for a credential file for registry authentication. 
 
The main motivation for this change is enabling to use Jib together with [Podman](https://podman.io/).

The 2 added locations are also mentioned in [`man containers-auth.json`](https://www.mankier.com/5/containers-auth.json#):

```
A credentials file in JSON format used to authenticate against container image registries. 
The primary (read/write) file is stored at ${XDG_RUNTIME_DIR}/containers/auth.json on Linux; 
on Windows and macOS, at $HOME/.config/containers/auth.json.

When searching for the credential for a registry, the following files will be read in sequence 
until the valid credential is found: first reading the primary (read/write) file, or the explicit override 
using an option of the calling application.  If credentials are not present, search in 
${XDG_CONFIG_HOME}/containers/auth.json, $HOME/.docker/config.json, $HOME/.dockercfg.
...
```

This logic seems aligned with the philosophy of Jib, which already [iterates through various locations](https://github.com/GoogleContainerTools/jib/issues/2260#issuecomment-580847849).

Jib also already follows XDG specification, for example [for storing its own config](https://github.com/GoogleContainerTools/jib/tree/master/jib-maven-plugin#user-content-global-jib-configuration). 

The resulting flow should hopefully be natural to most users: both Docker and Podman users would have their credential file picked up automatically in the default location of their tool. 

I updated documentation to mention the new configuration feature.

### CODE REVIEW

**Comment by ddixit14** [comment]
@sv3ndk Thank you for your contribution, really appreciate it. The team will review this after the holidays. 
Happy Coding 👯

**Comment by sv3ndk** [comment]
Thanks for the kind feed-back. Enjoy the holidays :)

**Comment by ddixit14** [comment]
You too. Happy Holidays!

**Comment by sv3ndk** [comment]
Hi @ddixit14 , I pushed a commit to fix the formatting issues, could you please re-trigger the CI workflow?

**Comment by sv3ndk** [comment]
Sorry, I'm realizing there was one remaining formatting issue that `./gradlew clean goJF`  had not fixed (I probably forgot the to "clean" first).
Now hopefully it should be correct. At least `./gradlew clean jib-plugins-common:verifyGoogleJavaFormat`  does not report anything on my host atm.

**Comment by chanseokoh** [comment]
Thanks for your contribution. I'm going to merge this once the tests pass, unless I hear back any concerns from you.

**Pull request merged**
