### PR TITLE
Bump min gradle version to 5.1 and fix deprecation warnings

### LINKED ISSUE #2166: Deprecation warning on AbstractArchiveTask methods
Getting a warning for these methods being deprecated.

```
> Task :jib-gradle-plugin:compileJava
/usr/local/google/home/tcordle/IdeaProjects/jib/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java:240: warning: [deprecation] getDestinationDir() in AbstractArchiveTask has been deprecated
              jarTask.getDestinationDir().toPath().resolve(jarTask.getArchiveName()));
                     ^
/usr/local/google/home/tcordle/IdeaProjects/jib/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java:240: warning: [deprecation] getArchiveName() in AbstractArchiveTask has been deprecated
              jarTask.getDestinationDir().toPath().resolve(jarTask.getArchiveName()));
                                                                  ^
2 warnings
```

### PR DESCRIPTION
**Pull request by TadCordle**
Fixes #2166.

### CODE REVIEW

**Comment by TadCordle** [comment]
Hang on, integration test failing...

**Comment by chanseokoh** [comment]
You should update https://github.com/GoogleContainerTools/jib/pull/2210/files#diff-aef8bf567c91df6622aa0ea29ed0c682R45 (assuming the API are available in 5.1). Actually, all of #2210 changes.

**Comment by chanseokoh** [comment]
Does the full integration test fail? Running actual Jib builds is the only way to know if the API is available in 5.1.

**Comment by TadCordle** [comment]
It failed on 5.0 but it doesn't anymore.

**Pull request merged**
