### PR TITLE
Lower verbosity of insecure registry failover

### LINKED ISSUE #778: Consider limiting warnings related to allowInsecureRegistries failover if too verbose
https://github.com/GoogleContainerTools/jib/pull/771#issuecomment-409943409

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #778.

### CODE REVIEW

**Comment by briandealwis** [comment]
Using INFO makes sense.  But I think the real problem with the logging is that it leaves me hanging: it's not clear whether the insecure-attempt worked!
```
[WARNING] Failed to connect to https://localhost:5000/v2/foo/blobs/sha256:077396f4e79fec38d66633aed03c94066e3ea8677fd7925b6c799ea676da2896 over HTTPS. Attempting again with HTTP: http://localhost:5000/v2/foo/blobs/sha256:077396f4e79fec38d66633aed03c94066e3ea8677fd7925b6c799ea676da2896
[WARNING] Cannot verify server at https://localhost:5000/v2/foo/blobs/uploads/. Attempting again with no TLS verification.
[WARNING] Failed to connect to https://localhost:5000/v2/foo/blobs/uploads/ over HTTPS. Attempting again with HTTP: http://localhost:5000/v2/foo/blobs/uploads/
[WARNING] Cannot verify server at https://localhost:5000/v2/foo/manifests/latest. Attempting again with no TLS verification.
[WARNING] Failed to connect to https://localhost:5000/v2/foo/manifests/latest over HTTPS. Attempting again with HTTP: http://localhost:5000/v2/foo/manifests/latest
```

**Comment by chanseokoh** [comment]
> it's not clear whether the insecure-attempt worked!

Make sense, and it's easy to log success. However, I think it is quite verbose and somehow unnecessary to confirm the success. With INFO, most people will not see or pay attention to them, especially if there was no error. If there is an error, it will fail right away.

**Comment by briandealwis** [comment]
I guess what would be better is that we figure this out once and then use that knowledge for all future requests, rather than rediscover the appropriate settings each time.

**Comment by chanseokoh** [comment]
That's a viable optimization. I'll create a new issue.

**Pull request merged**
