### PR TITLE
Upgrade to gradle 8.4, junit 5. Fix configuration cache issues.

### LINKED ISSUE #4062: Jib Gradle Plugin emits warning on gradle 8.2 due to referencing deprecated convention.
**Environment**:

- *Jib version:* 3.3.1
- *Build tool:* gradle
- *OS:* macos

**Description of the issue**:
When applying jib plugin to a project using gradle 8.2 (with `--stacktrace` enabled to show exact location) the following warnings are emitted: 
```
The Project.getConvention() method has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at org.gradle.api.internal.project.DefaultProject.getConvention(DefaultProject.java:593)
        at com.google.cloud.tools.jib.gradle.JibPlugin.lambda$apply$9(JibPlugin.java:187)
...
The org.gradle.api.plugins.Convention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#deprecated_access_to_conventions
        at org.gradle.internal.extensibility.DefaultConvention.logConventionDeprecation(DefaultConvention.java:398)
        at org.gradle.internal.extensibility.DefaultConvention.findPlugin(DefaultConvention.java:100)
        at org.gradle.internal.extensibility.DefaultConvention.getPlugin(DefaultConvention.java:89)
        at com.google.cloud.tools.jib.gradle.JibPlugin.lambda$apply$9(JibPlugin.java:188)
...
The org.gradle.api.plugins.JavaPluginConvention type has been deprecated. This is scheduled to be removed in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2/userguide/upgrading_version_8.html#java_convention_deprecation
        at org.gradle.api.plugins.internal.NaggingJavaPluginConvention.logDeprecation(NaggingJavaPluginConvention.java:185)
        at org.gradle.api.plugins.internal.NaggingJavaPluginConvention.getSourceSets(NaggingJavaPluginConvention.java:154)
        at com.google.cloud.tools.jib.gradle.JibPlugin.lambda$apply$9(JibPlugin.java:189)        
```

This appears to be due to loading the convetion here: https://github.com/GoogleContainerTools/jib/blob/master/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/JibPlugin.java#L187 

**Expected behavior**:
Jib gradle plugin  does not show deprecation warnings 

**Steps to reproduce**:
  1. Apply jib to a gradle project using gradle >= 8.2

### PR DESCRIPTION
**Pull request by wwadge**
This is a large MR, but mostly touches unit tests.

Fixes #4062 #3132 https://github.com/GoogleContainerTools/jib/issues/4070

### CODE REVIEW

**Comment by wwadge** [comment]
"kokoro-windows" check failed, but I don't have access to view the check's output.

**Comment by mpeddada1** [comment]
@wwadge We're having some issues with viewing our checks from the PR so pasting the error here:
```
Caused by: java.io.IOException: Unable to delete directory 'C:\tmpfs\src\github\jib\jib-build-plan\build'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - C:\tmpfs\src\github\jib\jib-build-plan\build\tmp\.cache\expanded\expanded.lock
  - C:\tmpfs\src\github\jib\jib-build-plan\build\tmp\.cache\expanded
  - C:\tmpfs\src\github\jib\jib-build-plan\build\tmp\.cache
  - C:\tmpfs\src\github\jib\jib-build-plan\build\tmp
	at org.gradle.internal.file.impl.DefaultDeleter.throwWithHelpMessage(DefaultDeleter.java:181)
	at org.gradle.internal.file.impl.DefaultDeleter.deleteRecursively(DefaultDeleter.java:114)
	at org.gradle.internal.file.impl.DefaultDeleter.deleteRecursively(DefaultDeleter.java:65)
	at org.gradle.api.tasks.Delete.clean(Delete.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
	... 147 more
```
From the initial glance, this looks like a concurrency issue. Could you try rebasing with main? We recently merged a change that updates gradle 8.2 (https://github.com/GoogleContainerTools/jib/pull/3892) and turns off parallel build in gradle due to another concurrency issue (https://github.com/GoogleContainerTools/jib/commit/0ab45c6f0507bc3c288b7145971c8791a522af60). This may help minimize the changes required in this PR and also (hopefully) address the issue.

**Comment by wwadge** [comment]
Bump for kokoro

**Comment by wwadge** [comment]
kokoro failing?

**Comment by mpeddada1** [comment]
Thanks for your patience on this @wwadge. We are currently working through an issue (unrelated to the PR) in our test infrastructure that is causing the jobs to stall.

**Comment by wwadge** [comment]
Updated by removing the workaround for gradle which only applies to v6 (this PR bumps to v8.3). PR still fails on kokoro-windows but I'm afraid I don't have access to logs so I'm going to need your help to diagnose what's up with that.

**Comment by loosebazooka** [comment]
The windows issues are related to windows fs things I believe:

```
Caused by: java.io.IOException: Unable to delete directory 'C:\tmpfs\src\github\jib\jib-build-plan\build'
  Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
  - C:\tmpfs\src\github\jib\jib-build-plan\build\tmp\.cache\expanded\expanded.lock
  - C:\tmpfs\src\github\jib\jib-build-plan\build\tmp\.cache\expanded
  - C:\tmpfs\src\github\jib\jib-build-plan\build\tmp\.cache
  - C:\tmpfs\src\github\jib\jib-build-plan\build\tmp
```

**Comment by loosebazooka** [comment]
This PR is almost too large to review. Can you find a way to separate the parts and we can look into getting it in? Perhaps separates out the gradle update, the plugin updates and Junit5 updates per project?

**Comment by wwadge** [comment]
Hmmm probably a little difficult though I'd agree the PR is pretty big, but most of it is silly stuff like removing "public" from test methods (junit 5 thing, triggered a lot of code smells in Sonar). If you think it's worth the effort I'll try to give it a shot

**Comment by loosebazooka** [comment]
Alright lemme give this review a shot and see how it goes.

**Review by loosebazooka — COMMENTED** [review]
so I started going through this, and it looks like there's still a lot of Junit4 (rules, assert, etc) -- I did not comment on all of them. I still think it makes sense to decouple the junit5 updates from the other changes related to cache configuration here.

**Comment by mpeddada1** [comment]
+1 to @loosebazooka. @wwadge would it be possible to split this up into smaller PRs? It looks like we are trying to solve multiple problems here but it may help to break it down problem by problem.

**Comment by wwadge** [comment]
@mpeddada1 yes I'll try to do that

**Comment by wwadge** [comment]
Closing in favour of: https://github.com/GoogleContainerTools/jib/pull/4139

**Pull request closed without merging**
