### PR TITLE
Overhaul gradle project properties test infra

### PR DESCRIPTION
**Pull request by chanseokoh**
We've gotten to the point where mocking Gradle APIs is not scaling.

### CODE REVIEW

**Comment by chanseokoh** [comment]
Ah, wait. Windows tests are failing due to an path issue.

**Comment by chanseokoh** [comment]
Tests are passing. Ready for review.

**Review by mpeddada1 — COMMENTED** [review]
Since we are making some refactoring changes to this test file anyways, how about converting the assertions to Truth?

**Comment by chanseokoh** [comment]
Converted to Truth. Much nicer.

**Comment by mpeddada1** [comment]
LGTM.

**Review by mpeddada1 — APPROVED** [review]

**Pull request merged**
