### PR TITLE
Adds control to push tags on existing images in target registry

### PR DESCRIPTION
**Pull request by karlmuscat**
Relevant issues: [#2360](https://github.com/GoogleContainerTools/jib/issues/2360)

Currently Jib pushes tags for all built images, irrelevant of whether the image is already 
present on the target registry. 

As highlighted by @loosebazooka [#2360](https://github.com/GoogleContainerTools/jib/issues/2360) 
this can be particularly annoying if some automated orchestrator is monitoring the registry
and releases any new tags found. This issue is especially prevalent in cases where the tags are
auto-generated by CI systems and added with every triggered build.

The idea is to give the user the ability to control this functionality by means of a switch/option. 
There might be use-cases where the current behaviour is preferable, eg, where the tags follow semantic 
versioning, or where the tags are not automatically generated. Hence, adding a switch seems to be 
a better solution rather than changing the current behaviour.

### CODE REVIEW

**Comment by karlmuscat** [comment]
@googlebot I signed it!

**Comment by loosebazooka** [comment]
Hey @karlmuscat usually for a change like this, we start off with just the proposal, and work on that before adding code. Sorry if my instructions were unclear. As there is some cost to adding and removing configuration, we need to review the design first before doing any coding work.

**Comment by karlmuscat** [comment]
@loosebazooka no problem at all. Do you need me to add some more detail to this PR to get the discussion going?

**Comment by loosebazooka** [comment]
@karlmuscat yes, can you create a new PR (you can leave this open) with just the design proposal?

**Comment by karlmuscat** [comment]
@loosebazooka Created new PR. Ill close this one to avoid confusion.

**Pull request closed without merging**
