### PR TITLE
maven-surefire-plugin 2.22.1

### PR DESCRIPTION
**Pull request by sullis**

### CODE REVIEW

**Comment by sullis** [comment]
issue:  https://github.com/GoogleContainerTools/jib/issues/1175

**Comment by briandealwis** [comment]
Thanks @sullis — did you have a particular reason to update surefire?  Would you mind updating `maven-failsafe-plugin` too?

**Comment by loosebazooka** [comment]
@briandealwis should we merge this?

**Comment by TadCordle** [comment]
I think we might as well. [Patch notes here](https://issues.apache.org/jira/secure/ReleaseNote.jspa?projectId=12317927&version=12343425) in case anyone wants to double check.

**Comment by briandealwis** [comment]
I think we should, but with the failsafe plugin too.  No point letting them diverge.

**Pull request merged**
