### PR TITLE
Detect bootJar task (Spring Boot fat JAR) and enable jar task to use the thin JAR

### PR DESCRIPTION
**Pull request by chanseokoh**
Implements https://github.com/GoogleContainerTools/jib/issues/1852#issuecomment-557275771 for Gradle. That is, this automatically enables https://github.com/GoogleContainerTools/jib/issues/1851#issuecomment-558293165 and makes use of the thin JAR by the `jar` task.

### CODE REVIEW

**Comment by chanseokoh** [comment]
> Would it make sense to start a document describing how jib handles different frameworks? <-- not necessary but could be nice to point specific framework users to?

I need to keep researching on it. Work in progress.

**Comment by ewirch** [comment]
The commit message says: "Detect bootJar task and enable jar task". But it does more. It also forces the classifier to 'original'.

https://github.com/GoogleContainerTools/jib/commit/a692b8b0cde1f982f6e28309dd08ca80460950e2#diff-aef8bf567c91df6622aa0ea29ed0c682R192

Why would you do so? This broke our build. I can't set the classifier manually any more. Except: not applying jib.

**Comment by chanseokoh** [comment]
Hi @ewirch,

When you apply the Spring Boot plugin, it will automatically disable the `jar` task. But sounds like you manually enabled it and set the `classifier` for either the `jar` task or the `bootJar` task. Could you share your `build.gradle` (or just the part related to configuring both the `jar` and `bootJar` tasks)?

**Comment by ewirch** [comment]
Sure thing. The important part is here:
```
jar {
    enabled = true
}

bootJar {
    archiveClassifier = 'boot'
}
```
This part is reused in multiple sub-projects of a multi project build. This will give use two artifacts per sub-project:
- `<name>.jar`
- `<name>-boot.jar`

We use both in different deployment scenarios. After updating jib to 2.0.0 we end up with:
- `<name>-original.jar`
- `<name>-boot.jar`

without a option to get the original naming back. Sure, we could adjust our build scripts to use `<name>-original.jar` instead. But it feels incorrect for a Docker image building plugin to interfere in such a way with the build configuration.

**Comment by chanseokoh** [comment]
@ewirch that makes sense. I think we can fix this easily. How about this?

Basically, if the classifier (or I guess `archiveClassifier`) of `bootJar` is set, then make Jib not set the `classifier` of the `jar` task. The only reason we set the `classifier` was to avoid `bootJar` and `jar` writing each JAR to the same location (overwriting each other).

**Pull request merged**
