### PR TITLE
Skips execution if packaging is 'pom'.

### LINKED ISSUE #734: Skip Mojo execution if packaging is POM.
This will help in multi-module Maven projects to skip containerizing a parent POM and only containerize modules that are actually applications to containerize.

### PR DESCRIPTION
**Pull request by coollog**
Fixes #734 

The code duplication will be taken care of by when we add a plugins-common framework (#478).

### CODE REVIEW

**Comment by loosebazooka** [comment]
I mean this is an easy way to fix the problem, but maven is configurable to avoid this.

**Comment by loosebazooka** [comment]
Should we only be executing on "jar" builds, and ignoring all other builds?

**Comment by coollog** [comment]
@loosebazooka We could, though we would want to enable "war" too when we take care of #431. However, we might want to allow for custom packaging types, though I'm not if people actually do that.

**Comment by loosebazooka** [comment]
Yeah, I'm not sure if I know what the right way is. Perhaps just leave it as is for now, maybe using the "jib" packaging type option can clear this up for most people.

**Comment by coollog** [comment]
Oops, forgot to add CHANGELOG. Will do in followup PR.

**Pull request merged**
