### PR TITLE
Update README.md to fix Spring Boot example link

### PR DESCRIPTION
**Pull request by isaacasensio**
Fix for https://github.com/GoogleContainerTools/jib/issues/1598

### CODE REVIEW

**Comment by isaacasensio** [comment]
I signed it!

**Comment by TadCordle** [comment]
There are a couple broken URLs in the [spring-boot example README](https://github.com/GoogleContainerTools/jib/blob/master/examples/spring-boot/README.md) as well, would you find fixing those too? I think the tweet link on L48 and the analytics badge on L54.

**Comment by isaacasensio** [comment]
Sure!

**Comment by isaacasensio** [comment]
> There are a couple broken URLs in the [spring-boot example README](https://github.com/GoogleContainerTools/jib/blob/master/examples/spring-boot/README.md) as well, would you find fixing those too? I think the tweet link on L48 and the analytics badge on L54.

Both links fixed.

**Pull request merged**
