### PR TITLE
🎁 Jib CLI > Add the windows install process with chocolatey 🎁 

### PR DESCRIPTION
**Pull request by adriens**
Hi, I'm a Jib fan.
Most of the time, i'm running Jib from `maven` and `gradle` , but recently I had to use it from command line. To help windows colleagues adopt it, I created a [Chocolatey package](https://community.chocolatey.org/packages/jib) to make the install process even easier under windows.

Hopefully you'll like it.

Thanks a lot for Jib, it helps us save so much time !

https://twitter.com/rastadidi/status/1380255793648312321

Kind Regards,
Adrien

### CODE REVIEW

**Comment by adriens** [comment]
CLA ✔️

**Comment by adriens** [comment]
image

**Comment by chanseokoh** [comment]
@adriens oh, awesome! Basically I don't really know what chocolatey is or have a way to test this, but sounds like this can be really helpful to the users.

For the CLA check, I also verified you are signed. I think you just need to leave a comment here with `@googlebot I signed it!` per instructions.

**Comment by adriens** [comment]
@googlebot I signed it!

**Comment by adriens** [comment]
@chanseokoh : thanks a lot for your very kind feedback.
Jib is an amazing tool, making us so productive 👏 🚀

**Comment by chanseokoh** [comment]
Thanks! Merging now.

**Pull request merged**
