### PR TITLE
 Adds BuildConfiguration#setExtraFilesLayerConfiguration.

### PR DESCRIPTION
**Pull request by coollog**
Part of #473

### CODE REVIEW

**Comment by coollog** [comment]
Will actually merge #503 first, since that makes `LayerConfiguration` able to take multiple entries.

**Comment by loosebazooka** [comment]
Should just generically accept layer configurations? Especially if that works towards our goal of library-fying jib.

**Comment by coollog** [comment]
@loosebazooka okay I can file a separate PR for that since that includes a lot more changes to the codebase.

**Comment by coollog** [comment]
Filed #516 , but we might want to have this first before that so that we can get the extra files feature out sooner.

**Pull request merged**
