### PR TITLE
Corrected groupId under Bind to a lifecycle

### PR DESCRIPTION
**Pull request by ganapathi004**
Doc Fixes

### CODE REVIEW

**Comment by ganapathi004** [comment]
I signed it!

**Comment by loosebazooka** [comment]
@ganapathi004 you must sign it with the same email address on your commit (or maybe you publicly available email on github?)

**Comment by chanseokoh** [comment]
Yeah, I checked the system and it doesn't say you signed the CLA.

**Comment by loosebazooka** [comment]
@ganapathi004 thanks for this change, unfortunately since you have not signed the CLA, we're going to have to close this PR. We will make the change in a new PR.

**Pull request closed without merging**
