### PR TITLE
Upgrade java11 to latest release # on Travis

### PR DESCRIPTION
**Pull request by mpeddada1**
For #2720

### CODE REVIEW

**Comment by loosebazooka** [comment]
would make sense to also make the mockito version update here to see if this fixes it?

**Comment by mpeddada1** [comment]
Yup, good point. Updated mockito-core.

**Comment by chanseokoh** [comment]
Shall we close this?

**Comment by mpeddada1** [comment]
Travis is no longer failing after mockito was upgraded to 3.5.7 (https://github.com/mockito/mockito/pull/2023) so we don't need to upgrade java anymore. Closing this PR.

**Pull request closed without merging**
