### PR TITLE
Migrate core classes in jib-core to classes in jib-build-plan

### PR DESCRIPTION
**Pull request by chanseokoh**
- Renamed `.jib.buildplan` pakcage to `.jib.api.buildplan` (in `jib-build-plan` subproject).
- Migrated some of the relocated classes in `jib-core`.

Renaming the following classes are may more disruptive, so I'll defer it to subsequent PRs.

- `LayerConfiguration` to `FileEntriesLayer`
- `LayerEntry` to `FileEntry`

~~Or, perhaps we should make a compromise and keep the current names? But the new names better fit into the build plan spec.~~ We'll mark `LayerConfiguration` and `LayerEntry` as deprecated while forwarding all calls to `FileEntriesLayer` and `FileEntry`.

I'll update CHANGELOG when we complete the entire migration.

---
UPDATE: the following issue is fixed by #2332.

~~Test failures: Skaffold tests in `jib-maven-plugin` (that run via `org.apache.maven.it.Verifier.executeGoal`) are failing, as it cannot find `jib-build-plan:jar:0.1.0-SNAPSHOT`. Not sure what's the difference with `jib-core`.~~

~~For example, `./gradlew :jib-maven-plugin:test --tests *CheckJibVersionMojoTest`:~~
```
    Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal com.google.cloud.tools:jib-maven-plugin:2.1.1-SNAPSHOT:_skaffold-fail-if-jib-out-of-date failed: Plugin com.google.c
loud.tools:jib-maven-plugin:2.1.1-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact com.google.cloud.tools:jib-build-plan:jar:0.1.0-SNAPSHOT
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:106)                                                                                                       
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 20 more                                                                                                                                                                                                
    Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin com.google.cloud.tools:jib-maven-plugin:2.1.1-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact com.googl
e.cloud.tools:jib-build-plan:jar:0.1.0-SNAPSHOT                                                          

```

### CODE REVIEW

**Comment by chanseokoh** [comment]
No test failure now. @loosebazooka not sure if I modified `build.gradle` correctly. I had to add `sourceProject(:jib-build-plan)` to `jib-maven-plugin` but not `jib-gradle-plugin`.

**Comment by loosebazooka** [comment]
So that's weird. You should require adding to both, maybe something is off again, lemme inspect

**Comment by loosebazooka** [comment]
Oh you know what, you should be using sourceProject to indicate that it is a source project, otherwise it will be imported as "implementation" and appear as a runtime dependency of the jib-gradle-plugin.

**Comment by chanseokoh** [comment]
Okay, sounds like it's correct to include `jib-build-plan` as `sourceProject`, regardless of whether there's no compilation or test failures.

**Comment by chanseokoh** [comment]
I think this is working now. Ready for review.

**Comment by loosebazooka** [comment]
> Okay, sounds like it's correct to include jib-build-plan as sourceProject in our plugin subprojects (jib-maven/gradle-plugin), regardless of whether there's no compilation or test failures.

Right because the final artifact and pom should be correctly generated.

**Comment by chanseokoh** [comment]
Yeah, sorry. I'll not bunch things up in the future. And feel free to ask me to break down a PR.

**Pull request merged**
