### PR TITLE
Improve entrypoint INHERIT doc for Maven

### LINKED ISSUE #2433: Maven plugin : improve the doc for container entrypoint INHERIT configuration
**Environment**:

- *Jib version:* 2.2.0
- *Build tool:* maven 3.2.5
- *OS:* Linux

**Description of the issue**:

**Expected behavior**:

**Steps to reproduce**:

  1. Create a pom.xml with the given plugin configuration (see below)
  2. When building, the following error is shown (see below)
 

**`jib-maven-plugin` Configuration**: 
```xml
        <configuration>
          <container>
            <entrypoint>INHERIT</entrypoint>
          </container>
        </configuration>
```

**Log output**: 
[ERROR] Failed to execute goal com.google.cloud.tools:jib-maven-plugin:2.2.0:build (build-dockerhub) on project img-mq: Unable to parse configuration of mojo com.google.cloud.tools:jib-maven-plugin:2.2.0:build for parameter entrypoint: Cannot assign configuration entry 'entrypoint' with value 'INHERIT' of type java.lang.String to property of type java.util.List -> [Help 1]
[ERROR]

**Additional Information**: This is expected behaviour. The workaround is to add a dummy element to turn the string into a list :
```xml
<entrypoint><entry>INHERIT</entry></entrypoint>
```

### PR DESCRIPTION
**Pull request by chanseokoh**
Fixes #2433.

OTOH, Gradle is OK and can take both `jib.container.entrypoint = 'INHERIT'` and `jib.container.entrypoint = [ 'INHERIT' ]`;

### CODE REVIEW

**Comment by TadCordle** [comment]
I wonder if this shows up anywhere else in our docs or examples; I could have sworn maven allowed skipping the inner tags for single-element lists.

**Comment by chanseokoh** [comment]
Huh, if that's the case, it's worth looking into this further.

**Comment by chanseokoh** [comment]
Yeah, `<entrypoint>INHERIT</entrypoint>` works for me. It may just be that old Maven versions have trouble with it.

**Comment by chanseokoh** [comment]
Confirmed. Maven 3.2.5 gives the error in #2433. Let me update the PR.

**Comment by loosebazooka** [comment]
hrmm... we end up suggesting a less user friendly option for maven users on the latest maven though?

**Comment by chanseokoh** [comment]
@loosebazooka updated the doc. What do you think?

**Comment by TadCordle** [comment]
I'm not sure about `dummy`, maybe go with `entry` or `token` or something?

**Comment by loosebazooka** [comment]
I like `<entry>` as well

**Pull request merged**
