### PR TITLE
Minor cleanups

### PR DESCRIPTION
**Pull request by chanseokoh**

### CODE REVIEW

**Comment by TadCordle** [comment]
What's with the travis failure?

```
/home/travis/build/GoogleContainerTools/jib/jib-gradle-plugin/src/main/java/com/google/cloud/tools/jib/gradle/GradleProjectProperties.java:238: error: cannot find symbol
          consoleLogger.log(Level.DEBUG, "Using JAR: " + jarPath);
```

**Comment by chanseokoh** [comment]
That's a complete non-sense. The /pr Travis build is for running builds after merging this PR, so perhaps something got confused or mixed up. I've rebased at HEAD, so let's see if this works.

**Comment by chanseokoh** [comment]
Aha, kind of merge conflicts, since `consoleLogger.log()` was introduced in a separate PR. Taken care of after merged with master.

**Comment by TadCordle** [comment]
Hmm, travis still failing, but because it's failing to unzip something.

**Comment by chanseokoh** [comment]
Suspected Travis cache corruption. Cleared the cache, reran Travis, and it seems working.

**Pull request merged**
